apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fetch-demo-template
  title: Fetch Example Template
  description: Demonstrates fetch:plain, fetch:plain:file, and fetch:template
  tags:
    - fetch
spec:
  owner: your-team@example.com
  type: service
  parameters:
    - title: Project Details
      properties:
        name:
          title: Project Name
          type: string
        description:
          title: Description
          type: string
        urlFile:
          title: File Path in Repo (e.g., path/to/file.txt)
          type: string
        repoUrl:
          title: Repository URL
          type: string
          default: https://github.com/hanumeshc/Files-Transfer
  steps:
    - id: fetch-example
      name: Fetch Example
      action: fetch:plain
      input:
        url: https://raw.githubusercontent.com/hanumeshc/Files-Transfer/main/README.md
        outputPath: ./README.md

    - id: fetch-single-file
      name: Fetch Single File
      action: fetch:plain:file
      input:
        url: ${{ parameters.repoUrl }}/contents/${{ parameters.urlFile }}?ref=main
        targetPath: ./single-file-fetched.txt

    - id: fetch-template-example
      name: Fetch and Process Template
      action: fetch:template
      input:
        url: https://github.com/hanumeshc/Files-Transfer/archive/refs/heads/main.zip
        values:
          projectName: ${{ parameters.name }}
          description: ${{ parameters.description }}
        outputPath: ./project

    - id: write-result
      name: Write Result
      action: filesystem:write
      input:
        path: ./result.txt
        contents: |
          Project Name: ${{ parameters.name }}
          Description: ${{ parameters.description }}
          Fetched single file: ${{ parameters.urlFile }}

  output:
    links:
      - title: Repository
        url: ${{ parameters.repoUrl }}
      - title: Project Folder
        url: ./project
