apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fetch-demo-template
  title: Fetch Example Template
  description: Demonstrates fetch:plain, fetch:plain:file, and fetch:template
  tags:
    - fetch
    - backstage
    - template
spec:
  owner: your-team@example.com
  type: service
  parameters:
    - title: Project Details
      properties:
        name:
          title: Project Name
          type: string
        description:
          title: Description
          type: string
        gitRepoUrl:
          title: Git Repository URL
          type: string
  steps:
    - id: fetch-example
      name: Fetch Example
      action: fetch:plain
      input:
        url: https://raw.githubusercontent.com/backstage/backstage/master/README.md
        outputPath: ./README.md

    - id: fetch-single-file
      name: Fetch Single File
      action: fetch:plain:file
      input:
        url: https://raw.githubusercontent.com/backstage/backstage/master/README.md
        targetPath: ./single-file-readme.md

    - id: fetch-template-example
      name: Fetch and Process Template
      action: fetch:template
      input:
        url: https://github.com/backstage/backstage/archive/refs/heads/master.zip
        values:
          projectName: ${{ parameters.name }}
          description: ${{ parameters.description }}
        outputPath: ./project

    - id: write-result
      name: Write Result
      action: filesystem:write
      input:
        path: ./result.txt
        contents: |
          Project Name: ${{ parameters.name }}
          Description: ${{ parameters.description }}
          README.md and template have been fetched successfully!

  output:
    links:
      - title: Repository
        url: ${{ parameters.gitRepoUrl }}
      - title: Project Folder
        url: ./project
