------------------
prometheus

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"prometheus","chart":"prometheus-11.16.2","component":"server","heritage":"Helm","release":"oes-sandbox"},"name":"oes-sandbox-prometheus-server","namespace":"oes"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":9090}],"selector":{"app":"prometheus","component":"server","release":"oes-sandbox"},"sessionAffinity":"None","type":"ClusterIP"}}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  creationTimestamp: "2024-07-08T14:21:41Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: prometheus
    chart: prometheus-11.16.2
    component: server
    heritage: Helm
    release: oes-sandbox
  name: oes-sandbox-prometheus-server
  namespace: oes
  resourceVersion: "325103136"
  uid: db385478-7951-41eb-9750-421376426193
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.177.125
  clusterIPs:
  - 172.20.177.125
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30214
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: oes-sandbox
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: internal-adb385478795141eb975042137642619-43859817.us-east-1.elb.amazonaws.com



------------------
grafana

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"oes-sandbox","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"10.2.2","helm.sh/chart":"grafana-7.0.19"},"name":"grafana","namespace":"oes"},"spec":{"ports":[{"name":"service","port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app.kubernetes.io/instance":"oes-sandbox","app.kubernetes.io/name":"grafana"},"type":"ClusterIP"}}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  creationTimestamp: "2024-07-08T14:21:40Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: oes-sandbox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.2.2
    helm.sh/chart: grafana-7.0.19
  name: grafana
  namespace: oes
  resourceVersion: "325100217"
  uid: dfe10206-b5b1-48ff-b1b6-821845a1c0c3
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.194.153
  clusterIPs:
  - 172.20.194.153
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: service
    nodePort: 32132
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: oes-sandbox
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: internal-adfe10206b5b148ffb1b6821845a1c0c-265330572.us-east-1.elb.amazonaws.com

-----------------
quay.io/opsmxpublic/ubi8-oes-gate:7eafeaa5-37



---
# Source: oes/templates/secrets/oes-gate-configmap.yaml
apiVersion: v1
stringData:
  gate.yml: |
    ok-http-client:
      interceptor:
        skipHeaderCheck: true
    retrofit:
      connectTimeout: 60000
      readTimeout: 60000
      callTimeout: 60000
      writeTimeout: 60000
      retryOnConnectionFailure: true
    services:
      opsmx:
        baseUrl: http://oes-sapor:8085
        enabled: true
      autopilot:
        baseUrl: http://oes-autopilot:8090
        enabled: true
      platform:
        baseUrl: http://oes-platform:8095
        userGroupApiPath: /platformservice/v1/users/{username}/usergroups/importAndCache
        enabled: true
      dashboard:
        baseUrl: http://oes-dashboard:8094
        enabled: true
      visibility:
        baseUrl: http://oes-visibility:8096
        enabled: true
      auditservice:
         baseUrl: "http://oes-audit-service:8097"
         enabled: true
      auditclient:
         baseUrl: "http://oes-audit-client:8098"
         enabled: true
      oesui:
        externalUrl: /ui/
      keel:
        enabled: false
      clouddriver:
        host: 0.0.0.0
        port: 7002
        baseUrl: http://spin-clouddriver-ro:7002
        enabled: true
      clouddriverCaching:
        host: 0.0.0.0
        port: 7002
        baseUrl: http://spin-clouddriver-caching:7002
        enabled: true
      clouddriverRo:
        host: 0.0.0.0
        port: 7002
        baseUrl: http://spin-clouddriver-ro:7002
        enabled: true
      clouddriverRoDeck:
        host: 0.0.0.0
        port: 7002
        baseUrl: http://spin-clouddriver-ro-deck:7002
        enabled: true
      clouddriverRw:
        host: 0.0.0.0
        port: 7002
        baseUrl: http://spin-clouddriver-rw:7002
        enabled: true
      deck:
        enabled: true
        host: 0.0.0.0
        port: 9000
        baseUrl: http://oes.example.ops.com
      echo:
        host: 0.0.0.0
        port: 8089
        baseUrl: http://spin-echo-worker:8089
        enabled: true
      echoScheduler:
        host: 0.0.0.0
        port: 8089
        baseUrl: http://spin-echo-scheduler:8089
        enabled: true
      echoWorker:
        host: 0.0.0.0
        port: 8089
        baseUrl: http://spin-echo-worker:8089
        enabled: true
      fiat:
        host: 0.0.0.0
        port: 7003
        baseUrl: http://spin-fiat:7003
        enabled: true
      front50:
        host: 0.0.0.0
        port: 8080
        baseUrl: http://spin-front50:8080
        enabled: true
      gate:
        host: 0.0.0.0
        port: 8084
        baseUrl: http://oes-gate.example.ops.com
        enabled: true
      igor:
        host: 0.0.0.0
        port: 8088
        baseUrl: http://spin-igor:8088
        enabled: true
      kayenta:
        host: 0.0.0.0
        port: 8090
        baseUrl: http://spin-kayenta:8090
        enabled: false
      orca:
        host: 0.0.0.0
        port: 8083
        baseUrl: http://spin-orca:8083
        enabled: true
      redis:
        host: 0.0.0.0
        port: 6379
        baseUrl: redis://wanv-san-0-oes-spinnaker-001-001.42ojqv.0001.use1.cache.amazonaws.com:6379
        enabled: true
      rosco:
        host: 0.0.0.0
        port: 8087
        baseUrl: http://spin-rosco:8087
        enabled: true
    user: {}
    cors:
      allowed-origins-pattern: ^https?://(?:localhost|oes.example.ops.com|spin.example.ops.com|opsmx.com)(?::[1-9]\d*)?/?
    ldap:
      enabled: true
      url: ldap://oes-sandbox-openldap:389
      managerDn: cn=admin,dc=example,dc=org
      managerPassword: opsmxadmin123
      groupSearchBase: ou=groups,dc=example,dc=org
      groupSearchFilter: member={0}
      groupRoleAttributes: cn
      userDnPattern: cn={0},dc=example,dc=org
    pipeline:
      rbac: false
    security:
      contentSecurityPolicy: "object-src 'none'; script-src 'unsafe-eval' 'unsafe-inline' https: http:;"
      basic:
        enabled: true
    saml:
      enabled: true
      issuerId: oesgate
      jksSecretName: oessamljks
      keyStore: /opt/spinnaker/saml/oessaml.jks
      keyStoreAliasName: saml
      keyStorePassword: changeit
      metadataSecretName: oesmetadataxml
      metadataUrl: /opt/spinnaker/saml/oesmetadata.xml
      redirectBasePath: /
      redirectHostname: oes-sbx.wureachnonprod.awswuintranet.net/gate
      redirectProtocol: https
      userSource: gate
    file:
      enabled: false
      url: /platformservice/v1/users/authenticate
    authn:
      mode: session
    google: {}
    redis:
      connection: redis://wanv-san-0-oes-spinnaker-001-001.42ojqv.0001.use1.cache.amazonaws.com:6379
      configuration:
        secure: true
    server:
      session:
        timeoutInSeconds: 7200
      tomcat:
        httpsServerPort: X-Forwarded-Port
        internalProxies: .*
        protocolHeader: X-Forwarded-Proto
        remoteIpHeader: X-Forwarded-For
    gate:
      installation:
        mode: common    #Allowed values are --> oes,common
    rbac:
      feature:
        application:
          enabled: true
    security:
      contentSecurityPolicy: "object-src 'none'; script-src 'unsafe-eval' 'unsafe-inline' https: http:;"
    spinnaker:
      extensibility:
        plugins:
        deck-proxy:
          enabled: true
          plugins:
            Opsmx.VerificationGatePlugin:
              enabled: true
              version: 1.0.1
            Opsmx.TestVerificationGatePlugin:
              enabled: true
              version: 1.0.1
            Opsmx.PolicyGatePlugin:
              enabled: true
              version: 1.0.1
            Opsmx.VisibilityApprovalPlugin:
              enabled: true
              version: 1.0.1
        repositories:
            opsmx-repo:
              url: file:///opt/spinnaker/plugins/plugins.json
              #url: https://raw.githubusercontent.com/OpsMx/spinnakerPluginRepository/v3.10.0/plugins.json
    spring.cloud.vault.enabled: false
    allowUnauthenticatedAccess:
      agentAPI: false
      webhooks: true
    message-broker:
      enabled: true
      username: rabbitmq
      password: encrypted:rabbitmqpassword:rabbitmqpassword
      host: rabbitmq-service
      port: 5672
      endpoint:
        name: rabbitmq
    logging:
      level:
        com.netflix.spinnaker.gate.security: INFO
        org.springframework.security: INFO
        org.springframework.web: INFO
        #com.netflix.spinnaker.gate.security: DEBUG
        #org.springframework.security: DEBUG
        #org.springframework.web: DEBUG
kind: Secret
metadata:
  name: oes-gate-config
  labels:
    app: oes
    component: gate
    heritage: "Helm"
    release: "oes-sandbox"
    chart: "oes-4.0.18"
