## Update the Appropriate RELEASENAME in all the fields of occurance ###
## The RELEASENAME should match which is provided during the Helm installation of SSD ##
apiVersion: batch/v1
kind: Job
metadata:
  name: RELEASENAME-minio-make-bucket-job
  labels:
    app: minio-make-bucket-job
    chart: minio-8.0.9
spec:
  template:
    metadata:
      labels:
        app: minio-job
        release: RELEASENAME
    spec:
      restartPolicy: OnFailure      
      volumes:
        - name: minio-configuration
          projected:
            sources:
            - configMap:
                name: RELEASENAME-minio
            - secret:
                name: RELEASENAME-minio
      serviceAccountName: "RELEASENAME-minio"
      containers:
      - name: minio-mc
        image: "quay.io/opsmxpublic/minio-mc:RELEASE.2020-11-25T23-04-07Z"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "/config/initialize"]
        env:
          - name: MINIO_ENDPOINT
            value: RELEASENAME-minio  
          - name: MINIO_PORT
            value: "9000"
        volumeMounts:
          - name: minio-configuration
            mountPath: /config
        resources:
          requests:
            memory: 128Mi
