{
 "title": "User Insights",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Active Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (username)(increase(active_users_count_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Users Triggered Pipelines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (username)(increase(trigger_pipeline_users_count_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Entities Triggered Pipelines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (entity)(delta(trigger_pipeline_entity_count_total[$__range]) > 0)) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(count by(username)(active_users_count_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Of Users Triggered Pipelines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (username)(floor(increase(trigger_pipeline_users_count_total[$__interval])))) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Login Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "floor(increase(failed_login_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of Entities That Triggered Pipelines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (entity)(delta(trigger_pipeline_entity_count_total[5m]) > 0)) OR on() vector(0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Apps By Pipeline Executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by (appName) (floor(increase(pipelines_execution_count_counter_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}